language: node_js
node_js:
  - lts/*
cache:
  directories:
    - ~/.npm
before_script:
  - npm install -g npm@latest
  - npm install -g expo-cli
  - apt-get -y install jq
script:
  - echo 'Installing the dependencies...'
  - yarn install --non-interactive
  - expo --version # expo-cli version
  - yarn list expo
  - echo 'Set unsplash api key to app.json'
  - jq '.expo.extra.unsplash="$UNSPLASH_API_KEY"' app.json > app.json.tmp && mv -f app.json.tmp app.json
  - echo 'Analysing app config...'
  - expo doctor --non-interactive
  - expo login -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}
  - expo publish --non-interactive --quiet --release-channel default
notifications:
  email:
    recipients:
      - ${EMAIL_BORGO}
      - ${EMAIL_DANIELE}
    on_success: change  # options: [always|never|change] default: changes
    on_failure: always  # options: [always|never|change] default: always
